// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5vKIy0odevK5fqW5Ovug47axHF-vSGPg',
    appId: '1:925922719836:web:63cf88f2be971d122d0e99',
    messagingSenderId: '925922719836',
    projectId: 'rast-34ec6',
    authDomain: 'rast-34ec6.firebaseapp.com',
    storageBucket: 'rast-34ec6.appspot.com',
    measurementId: 'G-GC0NGP8BRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHAsM0UOYgQqWo4BKa4yzpqqWibql8TOY',
    appId: '1:925922719836:android:8aca9f89590428e92d0e99',
    messagingSenderId: '925922719836',
    projectId: 'rast-34ec6',
    storageBucket: 'rast-34ec6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBchHcJFa64sn0GA1_jMwlFlfGzHrBy_2o',
    appId: '1:925922719836:ios:8ade5e7e7470508f2d0e99',
    messagingSenderId: '925922719836',
    projectId: 'rast-34ec6',
    storageBucket: 'rast-34ec6.appspot.com',
    iosBundleId: 'com.example.rast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBchHcJFa64sn0GA1_jMwlFlfGzHrBy_2o',
    appId: '1:925922719836:ios:42261d800d19cdfc2d0e99',
    messagingSenderId: '925922719836',
    projectId: 'rast-34ec6',
    storageBucket: 'rast-34ec6.appspot.com',
    iosBundleId: 'com.example.rast.RunnerTests',
  );
}
